version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: task-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: user@123
      MYSQL_DATABASE: taskdb
    ports:
      - "3307:3306"

  app:
    build: .
    container_name: task-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/taskdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: user@123
